const Footerpaths: any = [
  {
    id: 1,
    heading: 'General',
    links: [
      {text: 'Home', path: undefined, icon: undefined},
      {text: 'About Us', path: undefined, icon: undefined},
      {text: 'Blog', path: undefined, icon: undefined},
      {text: 'Press', path: undefined, icon: undefined},
      {text: 'Reporting', path: undefined, icon: undefined},
      {text: 'Integrations', path: undefined, icon: undefined},
      {text: 'iOS & Android', path: undefined, icon: undefined},
      {text: 'Mobile App', path: undefined, icon: undefined},
      {text: 'More Features', path: undefined, icon: undefined},
    ],
  },
  {
    id: 2,
    heading: 'Account',
    links: [
      {text: 'Login', path: undefined, icon: undefined},
      {text: 'Join', path: undefined, icon: undefined},
      {text: 'Forgot Password', path: undefined, icon: undefined},
      {text: 'Delete Account', path: undefined, icon: undefined},
      {text: 'Edit Account', path: undefined, icon: undefined},
      {text: 'Manage Subscription', path: undefined, icon: undefined},
      {text: 'Integrations', path: undefined, icon: undefined},
      {text: 'Manage Teams', path: undefined, icon: undefined},
      {text: 'Our Team', path: undefined, icon: undefined},
    ],
  },
  {
    id: 3,
    heading: 'Support',
    links: [
      {text: 'Create a ticket', path: undefined, icon: undefined},
      {text: 'Email us', path: undefined, icon: undefined},
      {text: 'Messaging', path: undefined, icon: undefined},
      {text: 'FAQ', path: undefined, icon: undefined},
      {text: 'Support Forums', path: undefined, icon: undefined},
      {text: 'API Documentation', path: undefined, icon: undefined},
      {text: 'Discord', path: undefined, icon: undefined},
      {text: 'Integrations', path: undefined, icon: undefined},
      {text: 'Mobile Help', path: undefined, icon: undefined},
    ],
  },
  {
    id: 4,
    heading: 'Legal',
    links: [
      {text: 'Terms and Conditions', path: undefined, icon: undefined},
      {text: 'Privacy Policy', path: undefined, icon: undefined},
      {text: 'Cookie Policy', path: undefined, icon: undefined},
      {text: 'GDPR', path: undefined, icon: undefined},
      {text: 'Billing Agreement', path: undefined, icon: undefined},
      {text: 'Our Promise To You', path: undefined, icon: undefined},
      {text: 'Integrations', path: undefined, icon: undefined},
      {text: 'iOS & Android', path: undefined, icon: undefined},
      {text: 'More Features', path: undefined, icon: undefined},
    ],
  },
  {
    id: 5,
    heading: 'Investors',
    links: [
      {text: 'Upcoming Rounds', path: undefined, icon: undefined},
      {text: 'Contact Us', path: undefined, icon: undefined},
      {text: 'Slidedeck', path: undefined, icon: undefined},
      {text: 'Current Investors List', path: undefined, icon: undefined},
      {text: 'Customer Management', path: undefined, icon: undefined},
      {text: 'Reporting', path: undefined, icon: undefined},
      {text: 'Integrations', path: undefined, icon: undefined},
      {text: 'iOS & Android', path: undefined, icon: undefined},
      {text: 'More Features', path: undefined, icon: undefined},
    ],
  },
];

export default Footerpaths;
